services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
